AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/ClassLength:
  Exclude:
    - "test/**/*"

Metrics/MethodLength:
  Exclude:
    - "test/**/*"

Metrics/AbcSize:
  Exclude:
    - "test/**/*"

Naming/MethodParameterName:
  MinNameLength: 1
  AllowedNames:
    - a
    - b
    - x
    - y
    - n
